### ISSUE TITLE
Change Menubar Name

### ISSUE THREAD

**Issue by vrMarc** [maxkostow/createchromeapp#2]
Is there a way this script can change the name in the OSX menubar from Chrome to the app name?

**Comment by alvint** [comment]
I was about to ask that myself.

**Comment by maxkostow** [comment]
Just saw this.

Looks like it is possible to alter the display name for an app, but I'm not sure how you could do it on a per-instance basis.

http://ansonalex.com/tutorials/change-application-display-name-in-mac-os-x/
