### ISSUE TITLE
How can I enable extensions?

### ISSUE THREAD

**Issue by Techienaut** [maxkostow/createchromeapp#3]
Hey maxkostow. I love this tool! Would you happen to know if there's an quick to tweak the script to allow extensions to be enabled while using the generated web app? I'd like to use "Plus for Trello" while using Trello. Don't bother though if there is no quick fix. And thanks again for making this.

**Comment by Techienaut** [comment]
After some research I realized that kiosk mode apps do not allow extensions to run within them, as it should be intended.

**Comment by linesarefuzzy** [comment]
I found that you can just open a new window, and it contains the hamburger icon where you can go to the extensions page. I installed a couple and they work for me.
